name:                indexed-queue
version:             0.1.0.0
github:              "sakshamsharma/indexed-queue"
license:             BSD3
author:              "Saksham Sharma"
maintainer:          "example@example.com"
copyright:           "2018 Saksham Sharma"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/sakshamsharma/indexed-queue#readme>

dependencies:
- base >= 4.7 && < 5
- either
- hashable
- hspec
- mtl
- pipes
- transformers
- unagi-chan
- unordered-containers

library:
  source-dirs: src

tests:
  indexed-queue-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - indexed-queue
